<program>			::=
						<bases><between><given><exponents>
<bases>				::=
						b
<between>			::=
						<lowerBound><upperBound>
<lowerBound>		::=
						<numberValue>
<upperBound>		::=
						<numberValue>
<given>				::=
						g
<exponents>			::=
						<exponent><exponent>
<exponent>			::=
						<numberValue><exponentParticle>
<numberValue>		::=
						<digit>
						|<digit><numberValue>
<digit>				::=
						0|1|2|3|4|5|6|7|8|9